# Generated by Django 3.1.7 on 2021-03-15 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=200, null=True)),
                ('DNI', models.CharField(default=None, max_length=15, null=True)),
                ('telefono', models.CharField(default=None, max_length=9, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('comercial', models.CharField(default=None, max_length=15, null=True)),
                ('CP', models.CharField(default=None, max_length=5, null=True)),
                ('provincia', models.CharField(default=None, max_length=30, null=True)),
                ('poblacion', models.CharField(default=None, max_length=30, null=True)),
                ('direccion', models.CharField(default=None, max_length=200, null=True)),
                ('numero', models.CharField(default=None, max_length=15, null=True)),
                ('portal', models.CharField(default=None, max_length=15, null=True)),
                ('escalera', models.CharField(default=None, max_length=15, null=True)),
                ('planta', models.CharField(default=None, max_length=15, null=True)),
                ('puerta', models.CharField(default=None, max_length=15, null=True)),
                ('fecha_contacto', models.DateField(default=django.utils.timezone.now)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_agendado', models.DateField(default=django.utils.timezone.now)),
                ('origen', models.CharField(choices=[('Cliente referenciado', 'Cliente referenciado'), ('Cliente de tienda', 'Cliente de tienda'), ('Cliente de cartera', 'Cliente de cartera')], default='Cliente referenciado', max_length=25, null=True)),
                ('segmento', models.CharField(choices=[('Empresa', 'Empresa'), ('Particular', 'Particular'), ('Autónomo', 'Autónomo')], default='Particular', max_length=25, null=True)),
                ('estado', models.CharField(choices=[('Llamado', 'Llamado'), ('Ofertado', 'Ofertado'), ('Agendado', 'Agendado'), ('No contesta', 'No contesta'), ('No interesa', 'No interesa'), ('Vendido', 'Vendido'), ('No existe', 'No existe')], default='Agendado', max_length=25, null=True)),
                ('operador', models.CharField(choices=[('Yoigo', 'Yoigo'), ('Jazztel', 'Jazztel'), ('Digi', 'Digi'), ('Movistar', 'Movistar'), ('Orange', 'Orange'), ('MasMovil', 'MasMovil'), ('Vodafone', 'Vodafone'), ('Pepephone', 'Pepephone'), ('Lowi', 'Lowi'), ('Lebara', 'Lebara'), ('Llamaya', 'Llamaya'), ('Otros', 'Otros')], default='MasMovil', max_length=25, null=True)),
                ('FMC_portaFIJO', models.PositiveSmallIntegerField(default=0, null=True)),
                ('FMC_FijoNuevo', models.PositiveSmallIntegerField(default=0, null=True)),
                ('PospagoMO', models.PositiveSmallIntegerField(default=0, null=True)),
                ('PospagoMB_DUOMB', models.PositiveSmallIntegerField(default=0, null=True)),
                ('CROSS_FijoPortado', models.PositiveSmallIntegerField(default=0, null=True)),
                ('CROSS_FijoNuevo', models.PositiveSmallIntegerField(default=0, null=True)),
                ('RENUEVO', models.PositiveSmallIntegerField(default=0, null=True)),
                ('RENUEVOSUBIDA', models.PositiveSmallIntegerField(default=0, null=True)),
                ('TV', models.PositiveSmallIntegerField(default=0, null=True)),
                ('SEGURO', models.PositiveSmallIntegerField(default=0, null=True)),
                ('ACCESORIOS', models.PositiveSmallIntegerField(default=0, null=True)),
                ('TERMLIBRE', models.PositiveSmallIntegerField(default=0, null=True)),
                ('CAMBIOTECNOLOGIA', models.PositiveSmallIntegerField(default=0, null=True)),
                ('PREPAGO', models.PositiveSmallIntegerField(default=0, null=True)),
                ('SEGURO_FAM', models.PositiveSmallIntegerField(default=0, null=True)),
                ('PEPENERGY', models.PositiveSmallIntegerField(default=0, null=True)),
                ('ENERGYGO', models.PositiveSmallIntegerField(default=0, null=True)),
                ('SMARTHOME', models.PositiveSmallIntegerField(default=0, null=True)),
                ('MOADICIONAL', models.PositiveSmallIntegerField(default=0, null=True)),
                ('comentarios', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comerciales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=200, unique=True)),
                ('cl_agendado', models.PositiveSmallIntegerField(null=True)),
                ('cl_llamado', models.PositiveSmallIntegerField(null=True)),
                ('cl_nocontesta', models.PositiveSmallIntegerField(null=True)),
                ('cl_noexiste', models.PositiveSmallIntegerField(null=True)),
                ('cl_nointeresa', models.PositiveSmallIntegerField(null=True)),
                ('cl_ofertado', models.PositiveSmallIntegerField(null=True)),
                ('cl_vendido', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_FMC_portaFIJO', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_FMC_FijoNuevo', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_PospagoMO', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_PospagoMB_DUOMB', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_CROSS_FijoPortado', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_CROSS_FijoNuevo', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_RENUEVO', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_RENUEVOSUBIDA', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_TV', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_SEGURO', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_ACCESORIOS', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_TERMLIBRE', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_CAMBIOTECNOLOGIA', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_PREPAGO', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_SEGURO_FAM', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_PEPENERGY', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_ENERGYGO', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_SMARTHOME', models.PositiveSmallIntegerField(null=True)),
                ('SUMA_MOADICIONAL', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
