# Generated by Django 3.1.7 on 2021-03-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20210315_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='comercial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CRM.comerciales', to_field='nombre'),
        ),
    ]
