# Generated by Django 3.1.7 on 2021-03-16 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20210316_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='comercial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CRM.comerciales'),
        ),
    ]
