# Generated by Django 3.1.7 on 2021-03-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_auto_20210316_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='CP',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(choices=[('Llamado', 'Llamado'), ('Ofertado', 'Ofertado'), ('Agendado', 'Agendado'), ('No contesta', 'No contesta'), ('No interesa', 'No interesa'), ('Vendido', 'Vendido'), ('No existe', 'No existe')], default='Agendado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='operador',
            field=models.CharField(choices=[('Yoigo', 'Yoigo'), ('Jazztel', 'Jazztel'), ('Digi', 'Digi'), ('Movistar', 'Movistar'), ('Orange', 'Orange'), ('MasMovil', 'MasMovil'), ('Vodafone', 'Vodafone'), ('Pepephone', 'Pepephone'), ('Lowi', 'Lowi'), ('Lebara', 'Lebara'), ('Llamaya', 'Llamaya'), ('Otros', 'Otros')], default='MasMovil', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='origen',
            field=models.CharField(choices=[('Cliente referenciado', 'Cliente referenciado'), ('Cliente de tienda', 'Cliente de tienda'), ('Cliente de cartera', 'Cliente de cartera')], default='Cliente referenciado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='poblacion',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='provincia',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='segmento',
            field=models.CharField(choices=[('Empresa', 'Empresa'), ('Particular', 'Particular'), ('Autónomo', 'Autónomo')], default='Particular', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
