# Generated by Django 3.1.7 on 2021-03-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20210318_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='CP',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='DNI',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
