# Generated by Django 3.1.7 on 2021-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_auto_20210318_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='CP',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='DNI',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='poblacion',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='provincia',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
